site_name: BitKey Electrum Server Checker
site_description: Check if an Electrum server is compatible with BitKey
site_author: Steven Geller
repo_url: https://github.com/StevenGeller/electrum-server-checker
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - User Guide:
    - Installation: guide/installation.md
    - Usage: guide/usage.md
    - Examples: guide/examples.md
  - BitKey Integration:
    - Overview: bitkey/overview.md
    - Server Requirements: bitkey/requirements.md
    - Security: bitkey/security.md
  - Development:
    - Contributing: development/contributing.md
    - Code of Conduct: development/code-of-conduct.md
    - API Reference: development/api.md
  - About:
    - Changelog: about/changelog.md
    - License: about/license.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true