name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the software are you running?
      placeholder: ex. 0.1.0
    validations:
      required: true
  - type: textarea
    id: server-info
    attributes:
      label: Server Information
      description: What Electrum server were you trying to check?
      placeholder: ex. electrum.blockstream.info
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code.
      render: shell
  - type: dropdown
    id: os
    attributes:
      label: What operating system are you using?
      options:
        - Windows
        - macOS
        - Linux
        - Other
    validations:
      required: true
  - type: dropdown
    id: python-version
    attributes:
      label: What Python version are you using?
      options:
        - Python 3.7
        - Python 3.8
        - Python 3.9
        - Python 3.10
        - Python 3.11
        - Other
    validations:
      required: true